# Spring properties
spring:
  data:
      mongodb:
        user: jchamorro
        password: jchamorro
        uri: mongodb://localhost:27017/db_diagrama_secuencia

# HTTP Server
server:
  port: ${port:8091}
